# Generated by Django 5.2 on 2025-05-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jssp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partno',
            name='car_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
