# Generated by Django 5.2 on 2025-05-05 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jssp', '0004_alter_partno_partno_ascii'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.CharField(blank=True, max_length=20, null=True)),
                ('order_type', models.CharField(blank=True, max_length=20, null=True)),
                ('order_start_id', models.IntegerField(blank=True, null=True)),
                ('order_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='delivery_order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lfdnr', models.IntegerField(blank=True, db_comment='发运单号', null=True)),
                ('vin', models.CharField(blank=True, db_comment='车架号', max_length=20, null=True)),
                ('part_color', models.CharField(blank=True, db_comment='零件颜色', max_length=20, null=True)),
                ('car_type', models.CharField(blank=True, db_comment='适用车型', max_length=20, null=True)),
                ('part_ascii', models.CharField(blank=True, db_comment='零件ASCII码', max_length=2, null=True)),
                ('mzeit', models.DateTimeField(blank=True, db_comment='制造时间', max_length=20, null=True)),
                ('position', models.CharField(blank=True, db_comment='位置', max_length=20, null=True)),
                ('knr', models.CharField(blank=True, db_comment='KNR', max_length=20, null=True)),
                ('factory', models.CharField(blank=True, db_comment='工厂', max_length=20, null=True)),
                ('product_line', models.CharField(blank=True, db_comment='产线', max_length=20, null=True)),
                ('order_no', models.CharField(blank=True, db_comment='订单号', max_length=20, null=True)),
                ('left_part_no', models.CharField(blank=True, db_comment='左侧零件', max_length=20, null=True)),
                ('left_part_name', models.CharField(blank=True, db_comment='左侧零件名称', max_length=20, null=True)),
                ('left_part_type', models.CharField(blank=True, db_comment='左侧零件类型', max_length=20, null=True)),
                ('left_part_code', models.CharField(blank=True, db_comment='左侧零件编码', max_length=20, null=True)),
                ('left_part_ascii', models.CharField(blank=True, db_comment='左侧零件ASCII码', max_length=2, null=True)),
                ('left_part_color', models.CharField(blank=True, db_comment='左侧零件颜色', max_length=20, null=True)),
                ('right_part_no', models.CharField(blank=True, db_comment='右侧零件', max_length=20, null=True)),
                ('right_part_name', models.CharField(blank=True, db_comment='右侧零件名称', max_length=20, null=True)),
                ('right_part_type', models.CharField(blank=True, db_comment='右侧零件类型', max_length=20, null=True)),
                ('right_part_code', models.CharField(blank=True, db_comment='右侧零件编码', max_length=20, null=True)),
                ('right_part_ascii', models.CharField(blank=True, db_comment='右侧零件ASCII码', max_length=2, null=True)),
                ('right_part_color', models.CharField(blank=True, db_comment='右侧零件颜色', max_length=20, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jssp.delivery_order')),
            ],
        ),
    ]
