# Generated by Django 5.2 on 2025-05-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='partno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partno', models.CharField(blank=True, max_length=20, null=True)),
                ('partname', models.CharField(blank=True, max_length=20, null=True)),
                ('parttype', models.CharField(blank=True, max_length=20, null=True)),
                ('partnum', models.CharField(blank=True, max_length=20, null=True)),
                ('partCode', models.CharField(blank=True, max_length=20, null=True)),
                ('partno_ascii', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
