# Generated by Django 5.2 on 2025-05-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jssp', '0002_partno_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partno',
            name='partColor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
