# Generated by Django 5.2 on 2025-05-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jssp', '0005_delivery_order_delivery_order_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_order_detail',
            name='left_part_sn',
            field=models.CharField(blank=True, db_comment='左侧零件SN', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='delivery_order_detail',
            name='right_part_sn',
            field=models.CharField(blank=True, db_comment='右侧零件SN', max_length=20, null=True),
        ),
    ]
